version: '3.9'

services:
  postgres:
    image: postgres:latest
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_PASSWORD=admin
      - POSTGRES_USER=admin
      - POSTGRES_DB=rezerwacjelotnicze
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U admin -d rezerwacjelotnicze" ]
      interval: 5s
      timeout: 5s
      retries: 5

  rezerwacje-lotnicze:
    build: .
    ports:
      - "8080:8080"
    depends_on:
      postgres:
        condition: service_healthy